-- liquibase formatted sql

-- changeset anton:2
CREATE TABLE bid
(
    id BIGINT NOT NULL generated by default as identity,
    primary key (id),
    bid_date timestamp default current_timestamp,
    bidder_name VARCHAR(255),
    lot_id bigint,
    foreign key (lot_id) references lot (id)
)